import { spawn } from "node:child_process";
import { access, open, realpath, rm } from "node:fs/promises";
import path from "node:path";
import { EnvironmentSecretProvider, loadLocalConfig } from "./local-config.mjs";
import { WindowsDpapiSecretProvider } from "./windows-dpapi-secret-provider.mjs";

function run(file, args, options = {}) { return new Promise((resolve) => { const child = spawn(file, args, { cwd: options.cwd, env: process.env, shell: false, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] }); let stdout = "", stderr = ""; child.stdout.on("data", (chunk) => stdout += chunk); child.stderr.on("data", (chunk) => stderr += chunk); const timer = setTimeout(() => child.kill(), options.timeoutMs ?? 10000); child.once("error", (error) => { clearTimeout(timer); resolve({ code: null, stdout, stderr: error.message }); }); child.once("exit", (code) => { clearTimeout(timer); resolve({ code, stdout, stderr }); }); }); }
async function writable(directory) { const file = path.join(directory, `.doctor-${process.pid}-${Date.now()}`); try { const handle = await open(file, "wx", 0o600); await handle.close(); await rm(file); return true; } catch { return false; } }
export async function runEnvironmentDoctor(configPath, options = {}) {
  const checks = []; let config;
  try { config = await loadLocalConfig(configPath); checks.push({ id: "config", status: "passed", detail: "Config version and path isolation verified." }); } catch (error) { return { status: "blocked", checks: [{ id: "config", status: "failed", detail: error.message }], readyForStandalone: false }; }
  const major = Number(process.versions.node.split(".")[0]); checks.push({ id: "node", status: major >= 22 ? "passed" : "failed", detail: `Node ${process.version}; required >=22.` });
  const runner = options.processAdapter?.run ?? run; const git = await runner("git", ["--version"], { timeoutMs: 10000 }); checks.push({ id: "git", status: git.code === 0 ? "passed" : "failed", detail: git.code === 0 ? git.stdout.trim() : "Git unavailable." });
  const dockerExecutable = options.dockerExecutable ?? (process.platform === "win32" ? path.join(process.env.ProgramFiles ?? "C:\\Program Files", "Docker", "Docker", "resources", "bin", "docker.exe") : "/usr/bin/docker"); let docker; try { await access(dockerExecutable); docker = await runner(dockerExecutable, ["info", "--format", "{{.ServerVersion}}"], { timeoutMs: 10000 }); } catch { docker = { code: null }; } checks.push({ id: "container", status: docker.code === 0 ? "passed" : config.execution.requireContainer ? "failed" : "warning", detail: docker.code === 0 ? `Docker daemon ${docker.stdout.trim()}.` : "Docker daemon unavailable." });
  for (const [name, directory] of Object.entries(config.roots)) { let canonical = null; try { canonical = await realpath(directory); } catch {} checks.push({ id: `root_${name}`, status: canonical && await writable(canonical) ? "passed" : "failed", detail: canonical ?? `Missing root: ${directory}` }); }
  const secretProvider = config.provider.secretProvider === "windows-dpapi" ? new WindowsDpapiSecretProvider(options.dpapiOptions) : new EnvironmentSecretProvider(options.environment ?? process.env); const secret = await secretProvider.status(config.provider.secretReference); checks.push({ id: "provider_secret", status: secret.available ? "passed" : "failed", detail: `${secret.reference}: ${secret.available ? "available" : "missing"}; value ${secret.value}.` });
  checks.push({ id: "model", status: config.provider.model ? "passed" : "failed", detail: config.provider.model || "Explicit model missing." });
  const failed = checks.some((item) => item.status === "failed"); return { status: failed ? "blocked" : checks.some((item) => item.status === "warning") ? "ready_with_warnings" : "ready", checks, readyForStandalone: !failed };
}
