import { randomBytes } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { configureSecretReference, createLocalConfig, EnvironmentSecretProvider, loadLocalConfig } from "../src/config/local-config.mjs";
import { WindowsDpapiSecretProvider } from "../src/config/windows-dpapi-secret-provider.mjs";
import { runEnvironmentDoctor } from "../src/config/environment-doctor.mjs";
import { cancelConfiguredSession, recoverConfiguredSession, runConfiguredSession, statusConfiguredSession } from "../src/app/standalone-app.mjs";
import { loadSchema } from "./validate-examples.mjs";

const [command, ...args] = process.argv.slice(2);
if (!command || !["init", "doctor", "request", "run", "status", "recover", "cancel", "secret-import"].includes(command)) {
  console.error("วิธีใช้:\n  kaveep init <config.json> <repository> <data-root> <model> [profile] [image]\n  kaveep doctor <config.json>\n  kaveep request <config.json> <authority.json> <mission.json> <request.json> <command...>\n  kaveep run <config.json> <authority.json> <mission.json> <command...>\n  kaveep status|recover|cancel <config.json> <durable-session-id>"); process.exit(2);
}
let result;
if (command === "init") { const [config, repositoryRoot, dataRoot, model, executionProfile = "node", image = "node:22-bookworm-slim"] = args; if (!model) throw new Error("init arguments are incomplete."); result = await createLocalConfig({ configPath: path.resolve(config), repositoryRoot: path.resolve(repositoryRoot), dataRoot: path.resolve(dataRoot), model, executionProfile, image }); }
else if (command === "doctor") { if (!args[0]) throw new Error("doctor requires config.json."); result = await runEnvironmentDoctor(path.resolve(args[0])); if (!result.readyForStandalone) process.exitCode = 1; }
else if (command === "request") {
  const [configFile, authorityFile, missionFile, outputFile, ...words] = args; if (!words.length) throw new Error("request arguments are incomplete.");
  const config = await loadLocalConfig(configFile); const authoritySnapshot = JSON.parse(await readFile(path.resolve(authorityFile), "utf8")); const missionLock = JSON.parse(await readFile(path.resolve(missionFile), "utf8"));
  if (authoritySnapshot.repositoryRoot !== config.repositoryRoot || missionLock.authoritySnapshotRef !== authoritySnapshot.authoritySnapshotId || authoritySnapshot.status !== "verified" || missionLock.status !== "active") throw new Error("Authority Snapshot, Mission Lock, and configured repository do not correlate.");
  result = { sessionRequestId: `standalone_session_request_${randomBytes(10).toString("hex")}`, schemaVersion: "1.0.0", command: words.join(" "), repositoryRoot: config.repositoryRoot, authoritySnapshot, missionLock, brain: { providerId: config.provider.id, model: config.provider.model, budget: { maxContextCharacters: config.defaults.maxContextCharacters, maxOutputTokens: config.defaults.maxOutputTokens, maxEdits: config.defaults.maxEdits, timeoutMs: 120000 }, maxContextFiles: 50 }, sandboxLimits: { maxFiles: 10000, maxDirectories: 2000, maxTotalBytes: 268435456, maxSingleFileBytes: 2097152, maxDepth: 30, maxPathLength: 512, maxLifetimeSeconds: 7200 }, workspaceIndex: { enabled: true, indexRoot: config.roots.workspaceIndex, limits: { maxFiles: 20000, maxDirectories: 5000, maxDepth: 30, maxFileBytes: 1048576 }, retrieval: { maxResults: 30, maxSnippetCharacters: 1000, maxContextCharacters: 30000 } }, loop: { maxAttempts: config.defaults.maxAttempts, semanticMaxAttempts: config.defaults.semanticMaxAttempts, maxSemanticFeedbackCharacters: 20000 }, container: { enabled: true, required: config.execution.requireContainer, executionProfile: config.execution.profile, image: config.execution.image, allowedImages: config.execution.allowedImages, operations: ["lint", "typecheck", "test", "build"], limits: { timeoutMsPerOperation: 300000, maxOutputBytes: 1048576, memoryMb: 2048, cpus: 2, pids: 256 } }, status: "proposed", createdAt: new Date().toISOString() };
  await writeFile(path.resolve(outputFile), `${JSON.stringify(result, null, 2)}\n`, { encoding: "utf8", flag: "wx", mode: 0o600 });
}
else if (command === "run") { const [configPath, authorityFile, missionFile, ...words] = args; if (!words.length) throw new Error("run arguments are incomplete."); result = await runConfiguredSession({ configPath, authorityFile, missionFile, command: words.join(" ") }, { proposalSchema: await loadSchema(path.resolve("schemas/engineering-proposal.schema.json")) }); if (!["awaiting_approval", "no_action"].includes(result.status)) process.exitCode = 1; }
else if (command === "secret-import") { const [configPath] = args; if (!configPath) throw new Error("secret-import requires config.json."); const config = await loadLocalConfig(configPath); const plaintext = new EnvironmentSecretProvider(process.env).resolve("OPENAI_API_KEY"); const provider = new WindowsDpapiSecretProvider(); const ciphertext = await provider.protect(plaintext); const directory = path.join(config.dataRoot, "secrets"); const reference = path.join(directory, "openai-api-key.dpapi"); await mkdir(directory, { recursive: true }); await writeFile(reference, `${ciphertext}\n`, { encoding: "utf8", flag: "wx", mode: 0o600 }); result = await configureSecretReference(configPath, "windows-dpapi", reference); }
else { const [configPath, sessionId] = args; if (!sessionId) throw new Error(`${command} arguments are incomplete.`); result = command === "status" ? await statusConfiguredSession(configPath, sessionId) : command === "recover" ? await recoverConfiguredSession(configPath, sessionId, { proposalSchema: await loadSchema(path.resolve("schemas/engineering-proposal.schema.json")) }) : await cancelConfiguredSession(configPath, sessionId); if (["blocked", "corrupted", "failed"].includes(result.status)) process.exitCode = 1; }
process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
